### PR TITLE
Added setting to also show email next to the name in the status bar

### PR DESCRIPTION
**Pull request by Wesztman**
First of, thanks for your work on this extension 😊

Switching between private and work accounts I use the same name but different emails.

Therefor I added this setting so that the user can choose to show the email next to the name in the status bar, it's in the same syntax as the configuration 😊 hope you'd like to upload a release of this 😊 tell me if I should change anything 👍

image

image

### CODE REVIEW

**Comment by Wesztman** [comment]
@stephtr , do you have any plans to merge this? :)

**Comment by stephtr** [comment]
You're welcome, thanks for your support & work!
Sorry, I somehow didn't receive any notification about this PR/repo.

Since from my point of view, this is an essential feature, I wouldn't even add a setting for that. [With the new version](https://github.com/stephtr/git-identity/blob/707e423ce3827e52977ad7263e557603509ec416/src/extension.ts#L15C2-L15C122) (published a few minutes ago), it automatically shows the email address, if there are more profiles with the same name available.

From your experience, would it make sense to hide the name, if all the profiles have the same author name?

**Comment by Wesztman** [comment]
> You're welcome, thanks for your support & work! Sorry, I somehow didn't receive any notification about this PR/repo.
> 
> Since from my point of view, this is an essential feature, I wouldn't even add a setting for that. [With the new version](https://github.com/stephtr/git-identity/blob/707e423ce3827e52977ad7263e557603509ec416/src/extension.ts#L15C2-L15C122) (published a few minutes ago), it automatically shows the email address, if there are more profiles with the same name available.
> 
> From your experience, would it make sense to hide the name, if all the profiles have the same author name?

Hi @stephtr 😊 I would not hide the name if all profiles have the same author name, at least not without an optional setting. 

I'm sad to say that I don't get any benefit from the new version atm 😅 I'm not actually using any profiles, I have different git clone aliases which set the author email in the local .git/config

So my normal `git clone` clones normal and uses my work email which is globally default and my alias `git gh-clone` sets the local cloned repo:s .git/config with my personal email. 

Therefor it would still be awsome to have some kind of way to show the email even if one does not use/have any profiles through this extension 😇

Cheers
Carl

**Comment by stephtr** [comment]
Ah I understand!
I'll combine your PR and update the extension probably tonight.

**Comment by stephtr** [comment]
The update is live 🙂

**Comment by Wesztman** [comment]
> The update is live 🙂

Thanks! 😁❤️

**Pull request merged**
